html: Add missing csp.h include in script.c
This fixes a compilation error where `csp_check_inline` and
`CSP_SCRIPT_SRC` were implicitly declared/undeclared.

```
/home/runner/work/wisp/wisp/src/content/handlers/html/script.c:607:10: error: implicit declaration of function ‘csp_check_inline’ [-Werror=implicit-function-declaration]
  607 |     if (!csp_check_inline(c->csp, CSP_SCRIPT_SRC)) {
      |          ^~~~~~~~~~~~~~~~
/home/runner/work/wisp/wisp/src/content/handlers/html/script.c:607:35: error: ‘CSP_SCRIPT_SRC’ undeclared (first use in this function); did you mean ‘HTML_SCRIPT_SYNC’?
  607 |     if (!csp_check_inline(c->csp, CSP_SCRIPT_SRC)) {
      |                                   ^~~~~~~~~~~~~~
```

Co-authored-by: tonestone57 <216575567+tonestone57@users.noreply.github.com>